// Tracking endpoint — Supabase, telegram_id (Bot API user.id) as primary key
// ONLY tracks authenticated users. No guest profiles.
//
// Both Mini App (initData) and Browser (OIDC) now use the SAME telegram_id:
//   - Mini App:  user.id from initData (Bot API ID, e.g. 854765520)
//   - Browser:   stored tg_id from localStorage, originally set by OIDC callback
//                using telegramUser.id (Bot API ID — NOT the OIDC sub)
//
// No username-based merging is needed anymore.
//
// IMPORTANT: we DO NOT create users for `web_*` IDs. Those are temp browser IDs
// generated by getBrowserUserId() before the user logs in. Tracking events for
// them would create ghost users in Supabase that fragment real user data.

const { getUser, recordEvent, getUserByOidcSub } = require('./_lib/supabase');
const crypto = require('crypto');

const ALLOWED_TYPES = [
  'page_views',
  'searches',
  'movies_opened',
  'categories_opened',
  'position_update',
  'favorite_added',
  'favorite_removed',
  'rate',
  'premium_refund'
];

function getClientIp(req) {
  const xff = req.headers['x-forwarded-for'];
  if (xff) return String(xff).split(',')[0].trim();
  if (req.headers['x-real-ip']) return String(req.headers['x-real-ip']);
  if (req.headers['x-vercel-ip']) return String(req.headers['x-vercel-ip']);
  return null;
}

function getUserAgent(req) {
  return req.headers['user-agent'] || '';
}

function validateInitData(initData, botToken) {
  if (!initData || !botToken) return null;
  try {
    const params = new URLSearchParams(initData);
    const hash = params.get('hash');
    if (!hash) return null;
    params.delete('hash');
    const dataCheckString = Array.from(params.entries())
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([k, v]) => `${k}=${v}`).join('\n');
    const secretKey = crypto.createHmac('sha256', 'WebAppData').update(botToken).digest();
    const calculatedHash = crypto.createHmac('sha256', secretKey).update(dataCheckString).digest('hex');
    if (calculatedHash !== hash) return null;
    const userJson = params.get('user');
    if (!userJson) return null;
    return JSON.parse(userJson);
  } catch (e) { return null; }
}

module.exports = async (req, res) => {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  if (req.method === 'OPTIONS') return res.status(200).end();
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });

  try {
    const body = req.body || {};
    const type = body.type;
    if (!ALLOWED_TYPES.includes(type)) return res.status(400).json({ error: 'Invalid type' });

    const ip = getClientIp(req);
    const ua = getUserAgent(req);
    let telegramId = null;
    let username = null;

    // 1) Mini App: validate initData → Bot API user.id (canonical telegram_id)
    if (body.initData) {
      const validatedUser = validateInitData(body.initData, process.env.TG_BOT_TOKEN);
      if (validatedUser) {
        telegramId = String(validatedUser.id);
        username = validatedUser.username || '';
      }
    }

    // 2) Browser: use stored userId (Bot API ID, set by OIDC callback)
    //    SKIP web_* IDs — they are temp browser IDs, not real Telegram IDs.
    //    Tracking them would create ghost users that fragment data.
    if (!telegramId && body.userId) {
      const uid = String(body.userId);
      if (uid.startsWith('web_')) {
        // Guest browser session — silently skip
        return res.status(200).json({ ok: true, skipped: true, reason: 'guest_web_id' });
      }
      telegramId = uid;
      username = body.username || '';
    }

    // 3) Legacy fallback: if userId looks like a long OIDC sub (length > 12),
    //    try to resolve the real user via oidc_sub column
    if (telegramId && telegramId.length > 12) {
      const resolved = await getUserByOidcSub(telegramId);
      if (resolved) {
        console.log('[track] Resolved legacy oidc_sub → telegram_id:', telegramId, '→', resolved.telegram_id);
        telegramId = resolved.telegram_id;
        if (!username && resolved.username) username = resolved.username;
      }
    }

    // 4) If still no telegramId → SKIP (guest)
    if (!telegramId) {
      return res.status(200).json({ ok: true, skipped: true });
    }

    // Record event
    const eventResult = await recordEvent(telegramId, type, {
      username: username || undefined,
      ip: ip || undefined,
      ua: ua || undefined,
      filmId: body.filmId || undefined,
      title: body.title || undefined,
      position: body.position || undefined, // for position_update
      duration: body.duration || undefined, // for position_update
      rating: body.rating || undefined, // for 'rate' event (1-5 stars)
      query: body.query || undefined,
      category: body.category || undefined,
      path: body.path || undefined
    });

    // Notify admin about new users (first-ever event from this telegram_id)
    if (eventResult && eventResult.isNewUser) {
      try {
        const { sendMessage } = require('./_lib/telegram');
        const adminIds = (process.env.ADMIN_IDS || '').split(',').map(s => s.trim()).filter(Boolean);
        const platformLabel = eventResult.platform === 'miniapp' ? '📱 Mini App' : '🌐 Браузер';
        const device = eventResult.device || 'неизвестно';
        const ipStr = eventResult.ip || '—';
        const usernameStr = eventResult.username ? '@' + eventResult.username : '—';
        const eventLabel = {
          page_views: 'просмотр страницы',
          searches: 'поиск фильма',
          movies_opened: 'открыл фильм',
          categories_opened: 'открыл категорию'
        }[eventResult.eventType] || eventResult.eventType;
        for (const adminId of adminIds) {
          try {
            await sendMessage(Number(adminId),
              '🎉 <b>Новый пользователь!</b>\n\n' +
              'ID: <code>' + telegramId + '</code>\n' +
              'Username: ' + usernameStr + '\n' +
              'Платформа: ' + platformLabel + ' — ' + device + '\n' +
              'IP: <code>' + ipStr + '</code>\n' +
              'Первое действие: ' + eventLabel,
              { reply_markup: { inline_keyboard: [[{ text: '🏠 На главную', callback_data: 'menu_main' }]] } }
            );
          } catch (_) {}
        }
        console.log('[track] Admin notified about new user:', telegramId);
      } catch (e) {
        console.warn('[track] Admin notification failed:', e.message);
      }
    }

    return res.status(200).json({ ok: true });
  } catch (e) {
    console.error('[track] error:', e);
    return res.status(500).json({ error: e.message });
  }
};
